// <auto-generated />
using System;
using CargoBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CargoBot.Migrations
{
    [DbContext(typeof(KargoDbContext))]
    partial class KargoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CargoBot.Models.Parcel", b =>
                {
                    b.Property<string>("TrackCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ArrivedAtChina")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("TrackCode");

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("CargoBot.Models.User", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CargoBot.Models.UserParcel", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId", "TrackCode");

                    b.HasIndex("TrackCode");

                    b.ToTable("UserParcels");
                });

            modelBuilder.Entity("CargoBot.Models.UserParcel", b =>
                {
                    b.HasOne("CargoBot.Models.User", "User")
                        .WithMany("SavedParcels")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CargoBot.Models.Parcel", "Parcel")
                        .WithMany("SavedByUsers")
                        .HasForeignKey("TrackCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CargoBot.Models.Parcel", b =>
                {
                    b.Navigation("SavedByUsers");
                });

            modelBuilder.Entity("CargoBot.Models.User", b =>
                {
                    b.Navigation("SavedParcels");
                });
#pragma warning restore 612, 618
        }
    }
}
